#server:
#  port: 9001
#
#spring:
#  application:
#    name: UserFoodApp-Service
#eureka:
#  client:
#    registerWithEureka: true
#    fetchRegistry: true
#    service-url:
#      defaultzone: http://localhost:8761/eureka/
#  server:
#    waitTimeInMsWhenSyncEmpty: 0
#  instance:
#    hostname: localhost